### ISSUE TITLE
Rust Version

### ISSUE THREAD

**Issue by killercup** [mrmonday/bitrust#2]
I just wanted to let you know that I wrote a rust program that uses the git2 crate to parse a git history for commits containing `[breaking-change]` and output JSON. This JSON can be shown in a simple angular.js app (just one HTML file with trivial code).

You can find the sources [here](https://github.com/killercup/bitrust/tree/rust).

I currently have no infrastructure to regularly run this on. You can do that though, if you want to.

**Comment by mrmonday** [comment]
Unfortunately it isn't running on my server, so I can't get this up and running unless it's either a simple shell script or python (or one of a few other options, it can only depend on the `git` command line tool though). This said, I would love to offer json output, and would accept a pull request adding support for it.

**Comment by killercup** [comment]
Using `git log` formatting to output something that looks like JSON only works for trivial cases, since it doesn't offer any escaping. I.e., it breaks at the first commit that uses `"`.

Another idea to run this might be to use a custom travis script for the gh-pages branch, that downloads and runs the compiled binary from the master branch.

**Comment by mrmonday** [comment]
Well the JSON output would need to be parsed and escaped separately, similar to what is already done with the HTML output.

Using Travis could work, but would require significant effort to get set up, and I'm not sure it's possible to do it without publicly exposing a private key.

**Comment by killercup** [comment]
Travis offers encrypted environment variable values. I'll probably look into this later this week. I think the only thing that needs to exist is a server that regularly triggers a build (which gets the gh-pages branch updated).

That's all one massive workaround though. What we really need is a Github API to search for commits ;)

**Comment by killercup** [comment]
BTW, I just pushed a manual "build" to http://killercup.github.io/bitrust/

**Comment by mrmonday** [comment]
I've stopped my version of bitrust from updating now, since GitHub pages had started spamming me with emails about the page not building. There's now a link to http://killercup.github.io/bitrust/, since it seems to be up to date.
